FORMAT: 1A
HOST: http://not.a.public.api/

# vnf-asterisk-controller

VNF asterisk controller API allows you to interact with discovered Asterisk instances, and manage configurations via push configuration.

Generally speaking this API does not have auth (you must otherwise protect it using firewalls or other methods) for now as it is a PoC. 

In general you access this using `GET` methods and tag parameters on paths to the API.

```
      { route: '/pushconfig/:boxid/:username',          method: this.pushConfig },
      { route: '/getconfig/:boxid/:username',           method: this.getConfig },
      { route: '/deleteconfig/:boxid/:username',        method: this.deleteConfig },
      { route: '/discover',                             method: this.discoverAll },

```

## Discover [/discover]

### List All Discovered Asterisk instances [GET]

+ Response 200 (application/json)

        [{"uuid":"9c220873-7e1f-4ae7-9aab-bc536e2bf974","ip":"172.19.0.4"}]

## Push configuration [/pushconfig/{instance_uuid}/{username}]

### Push a new endpoint configuration to an asterisk instance [GET]

Using the `uuid` as found using the `/discover` endpoint.

Parameters here are:

* `instance_uuid`: As found with `/discover` endpoint
* `username`: a nickname for the endpoint created


+ Response 201 (application/json)

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }